### PR TITLE
Read configuration from environment variables

### PR DESCRIPTION
**Pull request by codegoalie**
We are using rambler in a Docker container and found it easier to read the configuration values from the environment. I'm opening this PR to see if this would be something that you think would be beneficial to pull back into the project.

Let me know if I can do anything to clean it up or add more documentation to the README. 

Thanks for creating rambler!

### CODE REVIEW

**Comment by elwinar** [comment]
The idea is good, I think it would be simpler to use a library like envconfig.

Side question: would you be interested in an "official" docker image of rambler ?

Thanks for participating in making the world better.

**Comment by codegoalie** [comment]
@elwinar envconfig looks great! I didn't know it existed, but anything from Kelsey is pretty great. I will try to get this updated in the next few days.

Definitely having an official docker image would be great? Maybe it could support a volume for the migration files?

**Comment by elwinar** [comment]
This lib in particular is golden for anything related to Docker.

I'll make a docker image, and support whatever you need, if you be so 
kind as to open a new issue for it and describe your use case so I can 
have a better understanding of your needs (and don't "pollute" this MR).

Cheers,
Romain;

**Comment by codegoalie** [comment]
@elwinar 

Re-did this using envconfig, much cleaner! I also opened #20 with our current setup details.

**Pull request merged**
