### PR TITLE
Enables use of schema in PG

### PR DESCRIPTION
**Pull request by virmundi**
In PG there is a difference between databases and schemas. Rambler works fine as long as the user is creating in the default schema "public". This pull request enables differentiating between database and schemas. 

Unfortunately I'm new to Github pull requests. This change includes the environment variable integration feature as well.

### CODE REVIEW

**Comment by elwinar** [comment]
Can't you use the qualified name of the tables in your migrations? In don't use PostgreSQL myself, but reading the documentation about _schemas_ I don't feel like we need to do anything to support it.

**Comment by virmundi** [comment]
The migrations can use qualified schemas. The query for looking up the initialized migration name fails when using another schema other than public. I ran into that when I started to use Rambler this weekend. While I can name the migration table <schema>.migration or whatever, the query still fails in HasTable.

**Comment by elwinar** [comment]
In this case, I would be more in favor of writting the migration table as a qualified name and splitting it in the `HasTable` method of the driver rather than adding all thoses interface-breaking changes. It's simpler and you don't need anything else.

**Comment by virmundi** [comment]
If you do that, make sure the migration table creation includes that as well. You don't want to put migration into the public schema.

**Comment by virmundi** [comment]
I'm just going to use my fork. It does what I need.

**Pull request closed without merging**
